# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CreditCardListPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CreditCardListPractice
pod 'Kingfisher'
pod 'lottie-ios'
pod 'Firebase/Database'
end
