
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
# source 'https://cdn.cocoapods.org/'
target 'error' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for error
pod 'AlamofireNetworkActivityIndicator', '~> 3.1'
pod 'Alamofire', '~> 5.5'
pod 'SnapKit', '~> 5.0.0'
pod 'PanModal'
pod 'IQKeyboardManagerSwift'
pod 'Siren'
pod 'Firebase/Messaging'
pod 'Firebase/Analytics'
end
